### ISSUE TITLE
Muscat 7.1.1 quick fixes

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#1124]
...that do not work in 7.1...

- [x] Fix 670 person autocomplete
- [x] Fix holding "unapproved" wf_audit -> in 7.2 remove this unused field
- [x] people merge (NoMethodError) "undefined method `marc' for #<SourcePersonRelation>
- [x] Fix "inprogress" and "unpublished" legacy values in versions, also in holdings
- [ ] more to come...
